### ISSUE TITLE
Project website link is 404

### ISSUE THREAD

**Issue by Chirunos** [flathub/org.kde.CrowTranslate#2]
The current project website link on Flathub no longer works and should be changed to https://apps.kde.org/crowtranslate.

**Comment by Shatur** [comment]
Thank you! Fixed by https://invent.kde.org/office/crow-translate/-/commit/91d0450f53b5e96a40fef72acf3d3fa18ccb8290 (the file responsible for it located in the code repo).
Will talk about drafting a new release with KDE team.
